### ISSUE TITLE
CONFIG_PATH definition in iocxspress3-4Channel/defaultValueLoad.cmd

### ISSUE THREAD

**Issue by oksanagit** [epics-modules/xspress3#15]
CONFIG_PATH is defined to be at /home/xspress3/xspress3_settings/, while on my system it is at /etc/epics/xspress3/settings/4channel. This my first xspress3 unit I work with, but @lcdesilva says that this is the case for all xspress3 systems he worked with. 
I was wondering if this is true and if it could be updated. For the first time users it could take hours figuring out what is wrong.
Thanks.

**Comment by newville** [comment]
@oksanagit that's a good point.  I believe Quantum puts their config files in `/etc/xspress3/calibration/initial/settings` and that this is where their `xspress3-autocalib.py` program will but these settings files by default after a calibration.

I have always copied these to a place where the epics driver can use them and where they can be managed by the xspress3 account.  In fact, it is not unusual for me to swap detectors or play with the calibrations, so I want to keep multiple versions of these folders and use `/home/xspress3/xspress3_settings/current` as the current location for CONFIG_PATH, and use symlinks to point that to the real folder to be used. 

So, perhaps this is a "documentation issue"?  I think that having the Epics interface point CONFIG_PATH to somewhere like 
 `/home/xpress3/xspress3_settings/current` that is owned and written by the xspress3 account is useful, though the details (exact name of the folder, etc) are certainly open for suggestion.

**Comment by oksanagit** [comment]
I see your point about the calibrabration, I am not there yet. I will think about this as I continue my journey. 
- We could make the Make to copy this file at some point. The question is which one. If the epics layer is being developed before calibration is performed on this server, the calibrated file may not exist.  
- Leaving "as is" is also a possibility and letting newcomers to take an educational leap. I am open to add a paragraph to documentation at some later point. README?

**Comment by newville** [comment]
@oksanagit it might be reasonable to say that the configuration folder (contains many small binary files) should be called 'xspress3_setttings' and sit in the IOC folder.   The `CONFIG_PATH` in `st.cmd` would not change.  

But: then we'd have to put those settings files in .gitignore and each user would be required to copy ones appropriate for their detector/xspress3 combination to that folder. 

Either way, describing this "where to put the settings files" should be documented somewhere!

**Comment by lcdesilva** [comment]
@oksanagit yes, we should add the information in the README. 

QD IOC comes with the default path; /etc/epics/xspress3/settings/<n>channel and it adds a symbolic link to the location that @newville pointed out.

"
[desilva@xf07bm-ioc3 settings]$ pwd
/etc/epics/xspress3/settings
[desilva@xf07bm-ioc3 settings]$ ls -l
total 0
lrwxrwxrwx. 1 xspress3 xspress3 47 Aug 17  2018 6channel -> ../../../xspress3/calibration/initial/settings/
"

QDs calibration code will always put the files in that folder, I think. We could do a symbolic link to that folder from "/home/xspress3/xspress3_settings/"?

**Comment by oksanagit** [comment]
Hi,
The below paragraph, I think, would add clarity to the issue. I am not creating a PR for the README change, rather relying on the maintainer to decide where and how information should be presented. Please feel free elaborating, or rephrasing.  I think we can close this issue, as nothing needs to be fixed. 


During the boot time xspress3 ioc looks for the config file in ```/home/xspress3/xspress3_settings/``` defined by CONFIG_PATH.
Vendor default configs can be found at ```/etc/epics/xspress3/settings/[typeOfYourHW]```, or ones produced after detector calibration can be found at ```/etc/xspress3/calibration/initial/settings```.
You need to make IOC load these files by copying to $(CONFIG_PATH), creating a link, or changing CONFIG_PATH definition.

**Comment by oksanagit** [comment]
I would like to close this issue, since nothing to be done  and it is very old.
