### ISSUE TITLE
Enhancement: data arrays could/should be Float32

### ISSUE THREAD

**Issue by newville** [epics-modules/xspress3#2]
The MCA data arrays are currently represented as Float64.   Float32 arrays use half the space, and can represent numbers to 1e7 with integer accuracy.   Since the max detector count rate is in the MHz range, and peaks are generally spread over ~10 channels in the spectra, Float32 is likely to give perfect fidelity even for spectra counted for ~ 100 seconds even at the highest count rate.  At higher count rate, the loss of fidelity will be far smaller than the statistical noise level (square root of intensity) up until count times of about one year.   

The branch at https://github.com/newville/xspress3/tree/Float32_Data has this implemented.  It seems to be working, with MCA array data being Float32, and HDF5 data saved as Float32, and so on.  I'll test it more fully with synchrotron beam over the next two weeks, and can give a more complete report. 

I'm not sure whether it is preferable to have an option for Float64 or Float32, or to just pick one.

**Comment by AdamBark** [comment]
I think the reasons this hasn't been added are that upstream only supply 64 bit floats so it requires another conversion and that it is possible to change type with AD plugins anyway. As the branch doesn't seem to exist any more and this issue is quite old I'm closing it but feel free to reopen it if you disagree.

**Comment by newville** [comment]
@AdamBark I've reached acceptance on this.  Float64 is complete overkill for this data, but using even modest HDF5 compression through the AD HDF5 plugin compresses the data sufficiently that it doesn't much matter.
