### ISSUE TITLE
Compilation failed on Debian 10

### ISSUE THREAD

**Issue by devilkingsatan666** [epics-modules/xspress3#21]
Dear all,
I was compiling synApps downloaded with the script "assemble_synApps" from this repo against EPICS-7.0.5 on Debian 10 (x86_64) with gcc 8.3.0, and the following is the error I got. 

> make[5]: Entering directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/xspress3App/src'
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
make[6]: Entering directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/xspress3App/src/O.linux-x86_64'
/usr/bin/g++ -o xspress3App  -L/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/lib/linux-x86_64 -L/opt/epics/R70.5/base/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/areaDetector-master/ADCore/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/areaDetector-master/ADSupport/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/asyn-R4-41/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/autosave-R5-10-2/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/busy-R1-7-3/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/calc-R3-7-4/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/iocStats-3-1-16/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/seq-2-2-8/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/sscan-master/lib/linux-x86_64 -L/opt/epics/R70.5/synApps/support/xspress3-2-5/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/base/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/areaDetector-master/ADCore/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/areaDetector-master/ADSupport/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/asyn-R4-41/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/autosave-R5-10-2/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/busy-R1-7-3/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/calc-R3-7-4/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/iocStats-3-1-16/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/seq-2-2-8/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/sscan-master/lib/linux-x86_64 -Wl,-rpath,/opt/epics/R70.5/synApps/support/xspress3-2-5/lib/linux-x86_64           -rdynamic -m64         xspress3App_registerRecordDeviceDriver.o xspress3AppMain.o    -lxspress3Epics -lxspress3 -limg_mod -lNDPlugin -lADBase -lqsrv -lntndArrayConverter -lnt -lpvDatabase -lpvAccessIOC -lpvAccessCA -lpvAccess -lpvData -lnetCDF -lMagick++ -lcoders -lMagick -ljbig -ljp2 -lbzlib -lpng -lwebp -llcms -lttf -lwmf -lfilters -ltiff -lxml2 -lNeXus -lhdf5 -lhdf5_hl -lbitshuffle -lblosc -lszip -lzlib -ljpeg -lasyn -lautosave -lbusy -lcalc -ldevIocStats -lsscan -lseq -lpv -ldbRecStd -ldbCore -lca -lCom  -lpthread -lrt -lX11 -lXext
/usr/bin/ld: /opt/epics/R70.5/synApps/support/xspress3-2-5/lib/linux-x86_64/libimg_mod.a(img_mod_linux.o): relocation R_X86_64_PC32 against symbol `malloc@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[6]: *** [/opt/epics/R70.5/base/configure/RULES_BUILD:231: xspress3App] Error 1
make[6]: Leaving directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/xspress3App/src/O.linux-x86_64'
make[5]: *** [/opt/epics/R70.5/base/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
make[5]: Leaving directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/xspress3App/src'
make[4]: *** [/opt/epics/R70.5/base/configure/RULES_DIRS:85: src.install] Error 2
make[4]: Leaving directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC/xspress3App'
make[3]: *** [/opt/epics/R70.5/base/configure/RULES_DIRS:85: xspress3App.install] Error 2
make[3]: Leaving directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs/xspress3IOC'
make[2]: *** [/opt/epics/R70.5/base/configure/RULES_DIRS:85: xspress3IOC.install] Error 2
make[2]: Leaving directory '/opt/epics/R70.5/synApps/support/xspress3-2-5/iocs'
make[1]: *** [/opt/epics/R70.5/base/configure/RULES_DIRS:85: iocs.install] Error 2
make[1]: Leaving directory '/opt/epics/R70.5/synApps/support/xspress3-2-5'
make: *** [/opt/epics/R70.5/base/configure/RULES_DIRS:85: /opt/epics/R70.5/synApps/support/xspress3-2-5.install] Error 2

I changed some packages' versions in the script since I wanted to compile the applications for EPICS 7, and Here's the results.

> SUPPORT=R6-2
> ALLENBRADLEY=2.3
> ALIVE=R1-3-1
> AREA_DETECTOR=master
> ASYN=R4-41
> AUTOSAVE=R5-10-2
> BUSY=R1-7-3
> CALC=R3-7-4
> CAMAC=R2-7-3
> CAPUTRECORDER=master
> DAC128V=R2-10-1
> DELAYGEN=R1-2-2
> DXP=R6-0
> DXPSITORO=R1-2
> DEVIOCSTATS=3.1.16
> ETHERIP=ether_ip-3-2
> GALIL=V3-6
> IP=R2-21
> IPAC=2.16
> IP330=R2-10
> IPUNIDIG=R2-12
> LOVE=R3-2-8
> LUA=R3-0-1
> MCA=R7-9
> MEASCOMP=R2-5-1
> MODBUS=R3-2
> MOTOR=master
> OPTICS=R2-13-5
> QUADEM=R9-4
> SNCSEQ=2.2.8
> SOFTGLUE=R2-8-3
> SOFTGLUEZYNQ=R2-0-3
> SSCAN=master
> STD=R3-6-2
> STREAM=2.8.16
> VAC=R1-9-1
> VME=R2-9-3
> YOKOGAWA_DAS=R2-0-1
> XSPRESS3=2-5
> XXX=R6-2

**Comment by MarkRivers** [comment]
You need to uncomment this line in the IOC Makefile:
https://github.com/epics-modules/xspress3/blob/7ffb19ad224621fed179b8fb82723eb0590d0b85/iocs/xspress3IOC/xspress3App/src/Makefile#L21

This is that section of the Makefile, which describes exactly the error you are getting:
```
# Uncomment the USR_LDFLAGS line to avoid the following error which happens with newer versions of gcc
#    libimg_mod.a(img_mod_linux.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
#    /usr/bin/ld: final link failed: Nonrepresentable section on output
#USR_LDFLAGS_Linux += -no-pie
```

**Comment by newville** [comment]
@devilkingsatan666 I think that suggests that the version of libimg_mod.a (which comes from Quantum Detectors) is pretty old.    There is a newer version (of `libimg_mod.a` and `libxspress3.a`) from their rpm for RHEL/Centos7 epics-xspress3-devel-1-6.el7.x86_64.rpm.  I've put those in the `staticlibs_from_qd_xspress3_1.6` branch.  

Using these builds for me and appears to run correctly (tested only on CentOS7).  These newer versions were almost certainly compiled with a more recent version of glibc, may have better "relocatable symbols", and work better with gcc8+.

I'll make a PR to merge that branch, but if you can test it that would be very helpful.

**Comment by newville** [comment]
OK.   Maybe @liamoryan knows if there is a version of these static libraries built with a more recent compiler and with `-fPIC` to avoid this.  I believe that they only distribute packages for RHEL/CentOS 7, but it is probably reasonable to start thinking about a newer platform.

**Comment by devilkingsatan666** [comment]
After following the solution as mentioned by @MarkRivers, It now successfully compiles on Debian 10. Thank you so much for your help. (I actually successfully compiled the whole set of synchrotron applications downloaded with the script "assemble_synApps.sh" which one can get from this [repo](https://github.com/EPICS-synApps/support). Note that areaDetector, sscan, and motor should be changed to master branch.).

**Comment by newville** [comment]
@devilkingsatan666 As a general rule, automated builds from master branches is probably not a great idea.

For building Xspress3 support specifically, there is a build script at the top level of the repository (https://github.com/epics-modules/xspress3/blob/master/build_xspress3.py).  This fetches recent-and-known-to-work versions of the required Epics modules and builds a complete, stand-alone epics tree.   
Currently, the list of package versions used is from September 2020.

You might give that a try, though it does not (yet?) fix the -fPIC problem.

**Comment by MarkRivers** [comment]
> As a general rule, automated builds from master branches is probably not a great idea.

He only needed to do that because he changed the version of base from 3.15.6 in the original script to 7.0.5.  motor and sscan don't yet have tagged releases that are compatible with 7.0.5, but they will soon.

**Comment by newville** [comment]
Just to clarify, following the installation instructions at https://github.com/epics-modules/xspress3#installation
and using the `build_xspress.py` script would use `base 7.0.3.1` , not `base 3.15.6`.  

Xspress3 does not use the `motor` record.  

The build script does still build with the `sscan` record (version R2-11-3)  This gets defined in the IOC start-up scripts, but none of the example IOCs actually load the `sscan` record.  It's left mostly for legacy reasons and older beamlines that might still need an sscan record, but I am not aware of anyone adding it back in ;).

**Comment by devilkingsatan666** [comment]
Since the issue has been solved, I think it's time to close the issue. Thank you so much for your help.
